### ISSUE TITLE
Inquiry Regarding GPU Configuration for Running

### ISSUE THREAD

**Issue by XiudingCai** [wangf3014/SCLIP#1]
Hi there! Thank you for providing such an awesome project. I'm curious about the computational power utilized for the experiments in the paper. Could you please share details about the GPU configuration used? Thank you!

**Comment by wangf3014** [comment]
Hello! Thanks for your interest in our work. We run the model with 4 RTX3090 GPUs in the experiments, but actually it does not require too much computational power since there is no training involved. A single GPU with >12G memory would be sufficient for SCLIP inference.

**Comment by XiudingCai** [comment]
Thanks for the reply! I am gonna try it.
