### ISSUE TITLE
About post processing.

### ISSUE THREAD

**Issue by Colezwhy** [wangf3014/SCLIP#4]
Hi, thank you very much for your wonderful work！Which is very inspiring.
I wonder if the post processing is included following the evaluation procedure given in this repo?
I not, how should I utilize pamr in my evaluation process?

**Comment by wangf3014** [comment]
Set "pamr_steps" and "pamr_stride" in the config files like below:

> model = dict(
>     name_path='./configs/cls_voc21.txt',
>     pamr_steps=10,
>     pamr_stride=[8, 16],
> )
